### ISSUE TITLE
Problem when working with multiple choice of random values

### ISSUE THREAD

**Issue by Ludwiggle** [WolframResearch/WolframWebEngineForPython#3]
This form cannot  work

    list = RandomReal[{}, 3];

    FormPage[{"x" -> "Real",  "y" -> list} ,  #x + #y &]

because `list` gets updated right after the selection of `"y"`.  I think `list` should be updated only after submitting the whole form or after a refresh, not while still selecting the values to be submitted.

**Comment by riccardodivirgilio** [comment]
I agree, it cannot work. 

The problem is that the expression is evaluating every time on every request, it is "stateless".
There are several ways to to create a form that is doing some custom initialization that should not change between requests, one is to create an APIFunction that is generating the form. something like:

```
APIFunction[
 "seed" ->  <|"Interpreter" -> "String", "Required" -> False|>,
 If[
   MissingQ[#seed], 
   HTTPRedirect[CreateUUID["?seed="]],
   SeedRandom[#seed];
   FormPage[{"x" -> "Real", "y" -> RandomReal[{}, 3]}, #x + #y &]
   ] &
 ]

```

Let me know if you have any other question.

Thanks.

**Comment by Ludwiggle** [comment]
Thanks, it works, very ingenious.

But let me stress on a key aspect. You have certainly noted  that I defined `list` outside `FormPage`.
Indeed, in a mma notebook my code works as expected. The reason why that code does not work with `wolframwebengine` is not because `FormPage` gets refreshed on every request, it is because the whole index.wl script gets re-evaluated. 
I suspect this can be changed, so that only `FormPage` gets refreshed at requests, but not the whole index script. 

Thank You.

**Comment by riccardodivirgilio** [comment]
yes, by default all files are re-evaluated on every request, we think this is the right behavior for development mode. 
you can disable this behavior by using the documented --cached option.
when you run the server using --cached every file is evaluated only once, if you do that FormPage should not change during the kernel lifetime. 

you still need to use a SeedRandom, otherwise everytime you restart the server, or every time a request is dispatched to a different kernel you would get a different FormPage in any case.
